### ISSUE TITLE
이메일 인증

### ISSUE THREAD

**Issue by Limdongkeun** [spring-boot-toy-project-team/code-review-backend#22]
### 만들고자 하는 기능이 무엇인가요?
회원가입 또는 로그인 후 이메일로 회원 인증

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] 이메일 전송
2. [x] 삽입된 버튼을 누르면 인증 및 홈페이지 이동
3. [x] 버튼 css 처리

### 예상 작업 시간
ex) 3h

**Comment by parkyountaek** [comment]
동근님 머지는 했는데 컨트롤러쪽 uri가 validation / email-velidation 두 부분이 헷갈릴거 같아서 명칭을 조금 다르게 해야할 것 같아요
